version: "{build}"

clone_depth: 5

skip_tags: true

branches:
  except:
    - /^(osx|linux|jar|windows)$/

environment:
  ssh_secret:
    secure: rSGxPYhT1WpkysdoBRSgj65HwEu3ULsFCfOoP7zJ/YbaVihhK8RfjaHcHQi50JH0
  PYTHON: C:\Python36-x64
  BUILD_PY: .\build\build.py
  BUILD_ARGS: '--name="Ready to check" --results-title="Showing results" --page-template="site/NuPageEmitter.xml" --form-template="site/NuFormEmitter.xml" --about-file="site/nu-about.html" --script-file="site/nu-script.js" --stylesheet-file="site/nu-style.css"'
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11
    - JAVA_HOME: C:\Program Files\Java\jdk12

install:
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - java -version
  - python --version
  - python %BUILD_PY% update-shallow
  - appveyor-retry python %BUILD_PY% dldeps

build_script:
  - python %BUILD_PY% %BUILD_ARGS% build

test_script:
  - python %BUILD_PY% check
  - python %BUILD_PY% test
  - python %BUILD_PY% jar
  - bash -lc 'for file in build/dist/*.zip*; do touch $file.asc; done' # FIXME hack just to ensure the .asc files get uploaded during deploy
  - java -jar .\build\dist\vnu.jar .\build\dist\index.html
  - java -jar .\build\dist\vnu.jar .\site\nu-about.html
  - python %BUILD_PY% war

cache:
  # cache the dependencies folder, and invalidate the cache
  # if any of the files right of the arrow change
  - 'dependencies -> .appveyor.yml,%BUILD_PY%,build\build.xml'

before_deploy:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt resources\ssh_appveyor.enc -out resources\ssh_appveyor -secret %ssh_secret%
  - cmd: appveyor-tools\secure-file -decrypt resources\gpg_appveyor.enc -out resources\gpg_appveyor -secret %ssh_secret%
  - chmod 600 resources\ssh_appveyor
  - cat resources\ssh_known_hosts >> %userprofile%\.ssh\known_hosts
  - chmod 600 %userprofile%\.ssh\known_hosts
  - bash -lc 'rm -f build/dist/*.asc; gpg --import resources/gpg_appveyor; for file in build/dist/*.zip*; do gpg --yes -ab --local-user 6C976B92 --sign $file; done'
  - git config --local user.name "AppVeyor"
  - git config --local user.email "mike@w3.org"
  - bash -lc "GIT_SSH_COMMAND='ssh -i resources/ssh_appveyor' git push --delete git@github.com:validator/validator.git windows || true"
  - git tag -m windows -f windows

artifacts:
  - path: 'build\dist\vnu.*.zip'
    name: vnu.jar with JRE
  - path: build\dist\vnu.jar
    name: vnu.jar
    type: zip

deploy:
  tag: windows
  provider: GitHub
  auth_token:
    secure: kQDmkxCMEYfOefd3yGIfOTLL8e+w512Mv7tojXIVwH7Dgv0xx0n0mfdQXRFdKbXE
  artifact: RuntimeImageArtifacts
  draft: false
  prerelease: true
  force_update: true
  on:
    JAVA_HOME: C:\Program Files\Java\jdk11
